### ISSUE TITLE
Feature: Expose DMS setting

### ISSUE THREAD

**Issue by f3rno** [f3rno/bfx-hf-ui#5]
Expose the bitfinex exchange connection DMS flag as a user setting.

### TODO
* [x] create user setting field
* [x] set DMS based on value
* [ ] verify algos are not adversely affected (they will be, in strange ways)
* [ ] refactor algos where necessary for painless no-DMS

**Comment by f3rno** [comment]
Implemented in 3.0.4
